USE master
GO

IF EXISTS (SELECT * FROM sys.databases WHERE name = 'HolyBird')
    DROP DATABASE HolyBird
GO

CREATE DATABASE HolyBird
GO

USE HolyBird
GO

-- 1. DAILY
CREATE TABLE DAILY
(
	MaDaiLy		NVARCHAR(10) PRIMARY KEY,
	TenDaiLy	NVARCHAR(100), 
	SDT_DL		NVARCHAR(20),  
	DiaChiDL	NVARCHAR(255)
);
GO

-- 2. TAIKHOAN
CREATE TABLE TAIKHOAN (
	TenDangNhap		NVARCHAR(50) PRIMARY KEY,
	MatKhau			NVARCHAR(255) NOT NULL,
	LoaiTaiKhoan	NVARCHAR(20) DEFAULT N'Khách hàng',
	NgayTao			DATETIME DEFAULT GETDATE(),
	TrangThaiTK		NVARCHAR(20) DEFAULT N'Hoạt động'
);
GO

-- 3. LOAIPHONG 
CREATE TABLE LOAIPHONG (
	MaLoaiPhong		NVARCHAR(10) PRIMARY KEY,
	HinhThuc	NVARCHAR(50),
	Hang			NVARCHAR(50),
	MucGia		DECIMAL(18,2) DEFAULT 0, 
	
	CONSTRAINT CHK_LP_DonGia CHECK (MucGia >= 0)
);
GO

-- 4. PHIPHATSINH
CREATE TABLE PHIPHATSINH (
	MaPPS		NVARCHAR(10) PRIMARY KEY,		
	TenPPS		NVARCHAR(100),			
	GiaPhi		DECIMAL(18,2) DEFAULT 0
);
GO

-- 5. KHACHHANG
CREATE TABLE KHACHHANG (
	CMND		NVARCHAR(12) PRIMARY KEY,
	HoTenKH		NVARCHAR(100) NOT NULL,
	NgaySinhKH	DATE,
	SDT_KH		NVARCHAR(20),
	EmailKH		NVARCHAR(100),
	DiaChiKH	NVARCHAR(255),
);
GO

-- 6. NHANVIEN
CREATE TABLE NHANVIEN 
(
	MaNV		NVARCHAR(10) PRIMARY KEY,
	HoTenNV		NVARCHAR(50) NOT NULL,
	NgaySinhNV	DATE,
	SDT_NV		NVARCHAR(20),
	EmailNV		NVARCHAR(100),
	ChucVu		NVARCHAR(50),
	MaDaiLy		NVARCHAR(10),
	TenDangNhap	NVARCHAR(50), -- FK
	
	CONSTRAINT FK_NV_TK FOREIGN KEY (TenDangNhap) REFERENCES TAIKHOAN(TenDangNhap),
	CONSTRAINT FK_NV_DL FOREIGN KEY (MaDaiLy) REFERENCES DAILY (MaDaiLy)
);
GO

-- 7. PHONG 
CREATE TABLE PHONG (
	MaPhong			INT PRIMARY KEY,
	Tang			INT,
	MaLoaiPhong		NVARCHAR(10),
	TrangThai		NVARCHAR(20) DEFAULT N'Đang trống',
	
	CONSTRAINT FK_P_LP FOREIGN KEY (MaLoaiPhong) REFERENCES LOAIPHONG(MaLoaiPhong)
);
GO

-- 8. GIAODICH
CREATE TABLE GIAODICH (
	MaDoan			NVARCHAR(10) PRIMARY KEY,
	DaiDienDoan		NVARCHAR(12), 
	SoNguoi			INT DEFAULT 1,
	SoPhong			INT DEFAULT 1,
	NgayBD			DATETIME,
	NgayKT			DATETIME,
	MaNV			NVARCHAR(10),
	MaDaiLy			NVARCHAR(10), 
	TenDangNhap     NVARCHAR(50), 

	CONSTRAINT FK_GIAODICH_KHACHHANG FOREIGN KEY (DaiDienDoan) REFERENCES KHACHHANG(CMND),
	CONSTRAINT FK_GIAODICH_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
	CONSTRAINT FK_GIAODICH_DAILY FOREIGN KEY (MaDaiLy) REFERENCES DAILY(MaDaiLy),
	CONSTRAINT FK_GIAODICH_TAIKHOAN FOREIGN KEY (TenDangNhap) REFERENCES TAIKHOAN(TenDangNhap)
);
GO

-- 9. CT_GIAODICH 
CREATE TABLE CT_GIAODICH (
	MaCTGD				NVARCHAR(10) PRIMARY KEY,
	MaDoan				NVARCHAR(10),
	NgayBD				DATETIME,
	NgayKT				DATETIME,
	TongPhiPhatSinh		DECIMAL(18, 2) DEFAULT 0,
	ThanhTien			DECIMAL(18, 2) DEFAULT 0,
	TrangThaiGD			NVARCHAR(30) DEFAULT N'Chưa nhận phòng',
	CMND				NVARCHAR(12), 
	MaPhong				INT,
	MaThe				NVARCHAR(10),
	CaNhan				NVARCHAR(12),

	CONSTRAINT FK_CTGD_GIAODICH FOREIGN KEY (MaDoan) REFERENCES GIAODICH(MaDoan),
	CONSTRAINT FK_CTGD_PHONG FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong)
);
GO

-- 10. THETU 
CREATE TABLE THETU (
	MaThe			NVARCHAR(10) PRIMARY KEY,
	NgayCap			DATETIME DEFAULT GETDATE(),
	NgayHetHan		DATETIME,
	TrangThaiThe	NVARCHAR(30) DEFAULT N'Đang hoạt động',
	MaCTGD			NVARCHAR(10), 

	CONSTRAINT FK_THE_CTGD FOREIGN KEY (MaCTGD) REFERENCES CT_GIAODICH(MaCTGD)
);
GO

-- Thêm khóa ngoại cho CT_GIAODICH sau khi bảng THETU đã có
ALTER TABLE CT_GIAODICH
ADD CONSTRAINT FK_CTGD_THE FOREIGN KEY (MaThe) REFERENCES THETU(MaThe);
GO

-- 11. HOADON
CREATE TABLE HOADON
(
	MaHD			NVARCHAR(10) PRIMARY KEY,
	NgayLap			DATE DEFAULT GETDATE(),
	NVLap			NVARCHAR(10),
	TrangThaiHD		NVARCHAR(50) DEFAULT N'Chưa thanh toán',
	TongTien		DECIMAL(18, 2) DEFAULT 0,
	MaDoan			NVARCHAR(10),

	CONSTRAINT FK_HD_NV FOREIGN KEY (NVLap) REFERENCES NHANVIEN (MaNV),
	CONSTRAINT FK_HD_DOAN FOREIGN KEY (MaDoan) REFERENCES GIAODICH (MaDoan)
);
GO

-- 12. CT_PHIPS
CREATE TABLE CT_PHIPS (
	MaCTGD			NVARCHAR(10) NOT NULL,		
	MaDoan			NVARCHAR(10) NOT NULL,
	MaPPS			NVARCHAR(10) NOT NULL,
	SoLuong			INT DEFAULT 1,			
	ThanhTienPPS	DECIMAL(18,2) DEFAULT 0,
			
	CONSTRAINT PK_CT_PHIPS PRIMARY KEY (MaCTGD, MaPPS), -- Khóa chính kép
	CONSTRAINT FK_CT_PHIPS_MaCTGD FOREIGN KEY (MaCTGD) REFERENCES CT_GIAODICH(MaCTGD),
	CONSTRAINT FK_CT_PHIPS_MaDoan FOREIGN KEY (MaDoan) REFERENCES GIAODICH(MaDoan),
	CONSTRAINT FK_CT_PHIPS_MaPPS FOREIGN KEY (MaPPS) REFERENCES PHIPHATSINH(MaPPS)
);
GO

/*
---- 1. Xóa tất cả FOREIGN KEY constraints
DECLARE @sql NVARCHAR(MAX) = N'';

SELECT @sql += N'ALTER TABLE ' 
    + QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + '.' 
    + QUOTENAME(OBJECT_NAME(parent_object_id))
    + ' DROP CONSTRAINT ' + QUOTENAME(name) + ';'
FROM sys.foreign_keys;

EXEC sp_executesql @sql;

---- 2. Xóa tất cả TABLES
DECLARE @sql2 NVARCHAR(MAX) = N'';

SELECT @sql2 += N'DROP TABLE ' 
    + QUOTENAME(TABLE_SCHEMA) + '.' + QUOTENAME(TABLE_NAME) + ';'
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE';

EXEC sp_executesql @sql2;
*/

